mongo:
  connection-string: "dummy_conn_string"
  username: "dummy_username"
  password: "dummy_password"

arena:
  center:
    x: 0.5
    z: 0.5
  size: 840

rules:
  - "This is a rule."
  - "This is another rule."

# <n> = natural index
# <rule> = rule text
rule-style: "<bold><n>.</bold> <rule>"

hackable-crate-spawning:
  # spawn frequency in minutes
  # formula:
  # Let
  #  n = player count
  # f(n) = (rng(ceil - floor) + floor - n * scale) as int
  frequency:
    # the minimum time between spawns
    floor: 60
    # the maximum time between spawns
    ceil: 120
    # player count multiplier: the higher the player count, the more frequent spawns will be
    scale: 1.3

loot:
  tier-one:
    # SWORDS
    wooden_sword:
      chance: 0.2
    stone_sword:
      chance: 0.1
    # AXES
    wooden_axe:
      chance: 0.1
    stone_axe:
      chance: 0.05
    # ARMOR
    leather_helmet:
      chance: 0.2
    leather_chestplate:
      chance: 0.15
    leather_leggings:
      chance: 0.15
    leather_boots:
      chance: 0.2
    chainmail_chestplate:
      chance: 0.03
    chainmail_boots:
      chance: 0.05
    # RANGED
    bow:
      chance: 0.1
    arrow:
      chance: 0.1
      amount: 8
    # UTILITY
    fishing_rod:
      chance: 0.1
    # CONSUMABLES
    bread:
      chance: 0.1
      amount: 2
    carrot:
      chance: 0.1
      amount: 3
    porkchop:
      chance: 0.1
      amount: 2
    apple:
      chance: 0.1
      amount: 2
  tier-two:
    iron_sword:
      chance: 0.5
  airdrop:
    diamond_sword:
      chance: 0.75
    diamond_chestplate:
      chance: 0.5
    diamond_leggings:
      chance: 0.5
    diamond_axe:
      chance: 0.65
  hackable:
    netherite_sword:
      chance: 0.8
    netherite_axe:
      chance: 0.8

enchanting:
  basic:
    # Weapons
    swords:
      sharpness:
        1: 1
      sweeping:
        1: 1
      knockback:
        1: 1
    axes:
      sharpness:
        1: 1
      efficiency:
        1: 1
        2: 2
        3: 2
    bow:
      power:
        1: 1
      punch:
        1: 1
    crossbow:
      quick_charge:
        1: 1
      piercing:
        1: 1
    trident:
      loyalty:
        1: 1
      riptide:
        1: 1
    # Armor
    helmets:
      protection:
        1: 1
      thorns:
        1: 1
      projectile_protection:
        1: 1
    chestplates:
      protection:
        1: 1
      thorns:
        1: 1
      projectile_protection:
        1: 1
    leggings:
      protection:
        1: 1
      thorns:
        1: 1
      projectile_protection:
        1: 1
    boots:
      protection:
        1: 1
      thorns:
        1: 1
      projectile_protection:
        1: 1
      feather_falling:
        1: 1
        2: 2
  advanced:
    # Weapons
    swords:
      sharpness:
        2: 2
        3: 3
      sweeping:
        2: 2
        3: 2
      knockback:
        2: 2
      fire_aspect:
        1: 3
    axes:
      sharpness:
        2: 2
        3: 3
      efficiency:
        4: 2
        5: 2
    bow:
      power:
        2: 2
        3: 3
      punch:
        2: 2
      infinity:
        1: 3
      flame:
        1: 3
    crossbow:
      multishot:
        1: 1
      quick_charge:
        2: 2
        3: 3
      piercing:
        2: 2
        3: 3
        4: 4
    trident:
      loyalty:
        2: 2
        3: 3
      riptide:
        2: 2
        3: 3
    # Armor
    helmets:
      protection:
        2: 2
      thorns:
        2: 2
        3: 3
      projectile_protection:
        2: 2
    chestplates:
      protection:
        2: 2
      thorns:
        2: 2
        3: 3
      projectile_protection:
        2: 2
    leggings:
      protection:
        2: 2
      thorns:
        2: 2
        3: 3
      projectile_protection:
        2: 2
    boots:
      protection:
        2: 2
      thorns:
        2: 2
        3: 3
      projectile_protection:
        2: 2
      feather_falling:
        3: 3
        4: 4

upgrades:
  wooden_sword:
    to: stone_sword
    price: 1
  stone_sword:
    to: iron_sword
    price: 1
  iron_sword:
    to: diamond_sword
    price: 1
  wooden_axe:
    to: stone_axe
    price: 1
  stone_axe:
    to: iron_axe
    price: 1
  iron_axe:
    to: diamond_axe
    price: 1
  leather_helmet:
    to: chainmail_helmet
    price: 1
  leather_chestplate:
    to: chainmail_chestplate
    price: 1
  leather_leggings:
    to: chainmail_leggings
    price: 1
  leather_boots:
    to: chainmail_boots
    price: 1
  chainmail_helmet:
    to: iron_helmet
    price: 1
  chainmail_chestplate:
    to: iron_chestplate
    price: 1
  chainmail_leggings:
    to: iron_leggings
    price: 1
  chainmail_boots:
    to: iron_boots
    price: 1
  iron_helmet:
    to: diamond_helmet
    price: 1
  iron_chestplate:
    to: diamond_chestplate
    price: 1
  iron_leggings:
    to: diamond_leggings
    price: 1
  iron_boots:
    to: diamond_boots
    price: 1

token-trader:
  airdrop:
    price: 3
    display-material: tripwire_hook

npc-skins:
  basic-enchanter:
    signature: "PN2GAtnrVds8eyXI6dBzFUATwzF1A1cXi9KMj8HSxaoIO8SqQ3cm3B0ElXQxsAO1yGWnOLE1BN8eyQ3++jogrqWpv55BpvUv9ke1HKKo7YdAUQsFhN7SHe0GjpXDLDU/8RWZDcPyFpGb7br1LqIXDFzlNd7DdSX/MV47FD+vsNlSfYJOzFONoUc+MgrLaVegiwhrVTR+KA/UGfA1eu4yttoGcVBZcZvl9X2xMSfha6MOzly/c/NFbbwQmsSCCppj26DeTSf7hdW7rlJ2yUtfuzOPKM3v1hy0hWHeBNHgPn2keL/LAJvyD2hr38e1pKXoDF0MNI6jEbgf6jKZ3+fU6JVYo4yXKnFRU8mstM8HvyerEClnG2fedOLhh4429glspU25BmznHVIIHy3zObux/LIWFbZ1PIkPKULd15p1Xq0n6GEggRwtkYMHzh+JuNCEVEBX1D2HZepx4OCjtOiZd2kekAvFEowEAoelBbxzenwrRftLKLJCK2mluhH60lYoK407T+uiagb3dS3PGjey0L8nBQ7vMJ9qgC04XLO0S1Dpk7AGx/v/Nlp7AOQQ4qy5JXRhK1jAmleqh0kmBW1cq60n7hgzX/s8JnYscK7vt3vz8SFgOCQZjI01yDQlSFMrBVopyF7SmmyZ57Nbe7fyYMm6EU3tf3ZWRPSDLWURoTw="
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTY0NTE1ODY5NTI0NywKICAicHJvZmlsZUlkIiA6ICJhOGJhMGY1YTFmNjQ0MTgzODZkZGI3OWExZmY5ZWRlYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJDcmVlcGVyOTA3NSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82ZDU1ZmRjNWRkZDNkZjAyZGQ1ZjQ2MWE3MjQ4YmMyYTIyMzQ2NjYwNmJlMDI2MjVjNTc3Nzg3YWJhZWFhNDM5IgogICAgfQogIH0KfQ=="
  advanced-enchanter:
    signature: "PN2GAtnrVds8eyXI6dBzFUATwzF1A1cXi9KMj8HSxaoIO8SqQ3cm3B0ElXQxsAO1yGWnOLE1BN8eyQ3++jogrqWpv55BpvUv9ke1HKKo7YdAUQsFhN7SHe0GjpXDLDU/8RWZDcPyFpGb7br1LqIXDFzlNd7DdSX/MV47FD+vsNlSfYJOzFONoUc+MgrLaVegiwhrVTR+KA/UGfA1eu4yttoGcVBZcZvl9X2xMSfha6MOzly/c/NFbbwQmsSCCppj26DeTSf7hdW7rlJ2yUtfuzOPKM3v1hy0hWHeBNHgPn2keL/LAJvyD2hr38e1pKXoDF0MNI6jEbgf6jKZ3+fU6JVYo4yXKnFRU8mstM8HvyerEClnG2fedOLhh4429glspU25BmznHVIIHy3zObux/LIWFbZ1PIkPKULd15p1Xq0n6GEggRwtkYMHzh+JuNCEVEBX1D2HZepx4OCjtOiZd2kekAvFEowEAoelBbxzenwrRftLKLJCK2mluhH60lYoK407T+uiagb3dS3PGjey0L8nBQ7vMJ9qgC04XLO0S1Dpk7AGx/v/Nlp7AOQQ4qy5JXRhK1jAmleqh0kmBW1cq60n7hgzX/s8JnYscK7vt3vz8SFgOCQZjI01yDQlSFMrBVopyF7SmmyZ57Nbe7fyYMm6EU3tf3ZWRPSDLWURoTw="
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTY0NTE1ODY5NTI0NywKICAicHJvZmlsZUlkIiA6ICJhOGJhMGY1YTFmNjQ0MTgzODZkZGI3OWExZmY5ZWRlYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJDcmVlcGVyOTA3NSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS82ZDU1ZmRjNWRkZDNkZjAyZGQ1ZjQ2MWE3MjQ4YmMyYTIyMzQ2NjYwNmJlMDI2MjVjNTc3Nzg3YWJhZWFhNDM5IgogICAgfQogIH0KfQ=="
  storage:
    signature: "ilRhRUm0jm6YJmRT1wi1XOTg6IFNUakRc6aAQC1R/zMsoXP5qXt3Rm8wCfe3Ga+WGN9obq4p2hm2i0lGPtOFeZ1V2WfXzLBC266WPFpitFeo3ymOygDQdDK8Hgar3YrsaczidEQ3MaSFFMEud+tdzLDQwuc6DphaOghLIKrZQKEpuozDV3zPUWPrElXOnwsSGR440oq3YWk+e/2vHAeWKel1nBzcY4woxAfWwv70A44cnEXzomCrJD7jabik4Rsp74f7v2M7EYOaEdK+539R3va4IZ4V+KxkOtM80YIWVpXPUeVL4mozc8ql1lyqmeNDbqDRNJ+UxBW8k6sQkxO6nChoMaCMtPpyQRQ90HBgiaK4h2fbYVVzJqHXN8G6tm+5nWpizDSZgb43eMCZCgyvWOOdnFmFmQbK0L6NklGWjG/2CybSg4wRWDRoTKP6p8Q5BZFHuA5y223PaB0HpjQO1k2xRK7pWrQsP1BOgJIxdZQeo37te66e0hdU1SnW6sHBNtjM8+tdSnT9f+VcjAfgcHLOhXiabPmifDrrLB+jNYtia0/cCkRdsBGBxDU9Ro5ccMdZntjvNa8o4oAy9LPgKqD+FjHFnGcYuaO3lIbwhbafJ9FjROF9EpyI/rFO4+RhbdAT7ouA5/UC8P8nNq26l8x4ZAwZBOTs/FMhyG14KAo="
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTY1ODE3NzY2NTAyNSwKICAicHJvZmlsZUlkIiA6ICIzOTg5OGFiODFmMjU0NmQxOGIyY2ExMTE1MDRkZGU1MCIsCiAgInByb2ZpbGVOYW1lIiA6ICI4YjJjYTExMTUwNGRkZTUwIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzYyMzVkMDM1ZDgwODk3MDI3OTVlNDViZGQyZTI4ZTE0ZDA0OTkwOGJmYjIxYmZhMTk4ZDcwZmQ4ZmViNDAxZiIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9"
  upgrader:
    signature: "Ib9AF9NCfiTD6qxjEoMldjDKh5SWBfPddBBprtEcCFZY8KsGPX3qSaLy6bmYEnR1KjLmDR0XcuaMqHB4v4E7ZfiebJoBRSgwbZmCN7SMJTKRKbrgL1t/m2/Exo9C6UcGzy2fK/mRdyCu+a2YjHzdTv9BP8JzvvKuejq02IrfzF9IzpsRrvkfUPGAZ4Ukc9OgiRLmjznaM7+nCGUh7EaEvWqQxYGY1jT/DH0nj7W880WDNCLs5nWBzs/Ho8PDbOOgdVmpVDvWDbaEE0S7Q7AxHhTXRVNKyxk9vwa90keKz6kRRzUQnd+CmL2rNYmZ4ngSy3U/+yxSBYCvMJEEzQNZrizb0Zf9ciUNpysDc51HPBn8/lqDXI8E69Z96Ch+JfKxWuOQTJ1S2aSuI3yX5lwYwVeYyVTtk3v1PHvk3by7v5sf3lop9Q2w5UKNhSlDZwZ74dZ9k0oLw+luJ/OPsll1DUT95Ly3AoHPAyNyKsgaWI+IJJlpl8LM2tAHAv1sns1p8ZBgpRZH+8dI7yVhNI42GM6WIITUXK0PzUDxlHGfuaVAlP3LfUrFYMTfeeqrqO1QM6nt1fPrFd9XkcdcMJjYkMU5WZbifcl2RfGiv4SHr7LiFJl1f2XtFKdO0isnLyqGrwAczsbUdrIJzUjDheKSGZWfDLUPEim99hzsvyE/xfY="
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTU5MDE1NjYzNDYzOCwKICAicHJvZmlsZUlkIiA6ICI5MWZlMTk2ODdjOTA0NjU2YWExZmMwNTk4NmRkM2ZlNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJoaGphYnJpcyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iMmIxMmE4MTRjZWQ4YWYwMmNkZGYyOWEzN2U3ZjMwMTFlNDMwZThhMThiMzhiNzA2ZjI3YzZiZDMxNjUwYjY1IgogICAgfQogIH0KfQ=="
  join:
    signature: "Qc38Si3XIN0/lbBoAzH9YpqUxLXvAeMlqiDa7MgHnFVM8tJyM8r/M4OWcPqIK/duF+Kbc02bfptRzTq26Pf6lhQ5sZ0JHUhikMhUOe8GyMjLJkQTJjmww682oIQOARwLQKTQzV1GJyJCCZ5GqBmF6QWA2DA0cgJx1xDI7/0LeB3SfWgv02628HiEbZecMYHyGbeW4kTCerQp4frZXpVEPcYfdNsAJaknUDkCyNeN1SLYpyTPx5uL4ajN4L30H8Aphl1ro+MbCxhvqedmOSQavwWXy1feCineU1A89Ch/ksC/u4QNqOr1QLY8Nb1wP9QEtdZG8PKdVk+aPrG2Z5pkTYntxUss5TTHw0jZ4cllUBEEOEpWUuybnF1JPS5fKH/Mb3R9UuhSAXVRIbwreWJLeU7ihiUjxHJPGSjVt9YPT0Wsgfppo0/nvfeyJVSz7cpdeUi9AZ/rlBNyGGLdzmLuX6SxWIBI44C8i0U3m2hszUUF0tF5+Dpf9UCMMfVNowH9Uz/DEKQ4ec+A7AkWXIck58SMp73xG50vR9ZjDCCKAIA3OXWD4MVOiIjJFwSA7s8YJZULKRHiWsaAXgcL5quSeLQkFh1ySNaL05tEa3bZP2DsS5Yx4t3zqPUMTgJdmda1na8GjA5pGBaPN7lmMmPdjj45VoA7l9pHjKZqHkxP60U="
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTY1OTE2NjY5OTc3NiwKICAicHJvZmlsZUlkIiA6ICIyM2YxYTU5ZjQ2OWI0M2RkYmRiNTM3YmZlYzEwNDcxZiIsCiAgInByb2ZpbGVOYW1lIiA6ICIyODA3IiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzI3NGZiNzk1ZTI2MjA2YTJlNGJkZGUwYjI3Y2M0YjYyYzAzNDdhNGU2ZDc4NGFiZDU1MTRjZjc2YzM2OWM2MjciCiAgICB9CiAgfQp9"
  token-trader:
    signature: "UGCsitAoYNvUd+1e/ly1cv4BV8knNYSiDijsTy1SV19D8qDSS1X+c7nQkwy0W2qhOlQzfkxuZhulJZnMISj4cwdcOQV25mwlBvU4aSrHaVqWdTycpCMsZ9Ao55uetGchjCfmcrpHTeYQcrAWIcLyfcMuW1omyMJJtU+d2IqvjDrofD4tdJuYMl8R8RTBTi+c9qI87DFITg0nbkXcSFsjp2rlVeWhig2OTOu2FkjkJ5v019XR6YH+KCL5VUqAYzyNGE6eNmRSqOsF4xkOgoO5j9TPHXZxHPtDVnteMbU73lpcAutdaAwXczo/cCqb/jDGrkEC6s2tZpXYkqYazS/pBOJZrn1VGDQ5Cb2lqsAQhPC9DYy5l/qUHXaaGoP/foc0ELBXYhgQGmxv4g8yduLF7sijtzO9ZlVHaS5YvbZ9HZecOLHK8SIfetsu6CiUw1Hl6IlinfTFpg1vACCwA/EQRyR9fl4iV78SmCn1313wleCbkNIW3j60mt18nAg84IX242rY7l8vJhgO0iKK3zlPp5An1Hm3dTkbo5vV6PVB6lDGn6n+XWJZeGzrwqiFg8bE4RWvxMVUrfafA1wSXKmRVw7OyTFnMge6g05NoEVXnovvGlDVFuPW9aBc5NSDkl3XHBgnQaHVXFBuV5t+DaShgX7ImWdzaV7PeVEhBDTIfWc="
    texture: "ewogICJ0aW1lc3RhbXAiIDogMTU5MTMxODQwMTk2MCwKICAicHJvZmlsZUlkIiA6ICI1NjY3NWIyMjMyZjA0ZWUwODkxNzllOWM5MjA2Y2ZlOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJUaGVJbmRyYSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iZWUwMzMyMDI1M2MyYThmOGFjNmZkZGI0ZGM0ZjMwMTA3OTQ3ZmQ0MWIwN2Y3MjY1YjA1ZmE4NTU2YTYxNDU3IgogICAgfQogIH0KfQ=="

