name: Survive
version: '${project.version}'
main: dev.dpvb.survive.Survive
api-version: 1.19
authors: [ dpvb ]
description: '${project.description}'
depend:
  - Citizens
  - Multiverse-Core
softdepend:
  - PlaceholderAPI
  - HolographicDisplays
libraries:
  - cloud.commandframework:cloud-paper:1.7.0
  - cloud.commandframework:cloud-annotations:1.7.0
  - org.mongodb:mongodb-driver-sync:4.6.1